apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
          - name: PMA_USER
            value: root
          - name: PMA_HOST
            value: wp-db
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name : mariadb-pass
                key: password
        ports:
        - containerPort: 80
          name: phpmyadmin
#        lifecycle:
#          postStart:
#            exec:
#              command: ["git", "clone", "https://github.com/qhoa/wp.git", "/app"]