apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: qhoa83/wordpress
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: WP_DB_NAME
            value: wordpress
          - name: WP_DB_USER
            value: wp-user
          - name: WP_DB_HOST
            value: wp-db
          - name: WP_DB_PASS
            valueFrom:
              secretKeyRef:
                name : mariadb-pass
                key: password
        ports:
        - containerPort: 80
          name: wordpress
#        lifecycle:
#          postStart:
#            exec:
#              command: ["git", "clone", "https://github.com/qhoa/wp.git", "/app"]
        volumeMounts:
          - name: wordpress-ps-storage
            mountPath: "/app"
      volumes:
        - name: wordpress-ps-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim