apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"        
        env:
          - name: MYSQL_DATABASE
            value: wordpress
          - name: MYSQL_USER
            value: wp-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-pass
                key: password        
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-pass
                key: password
        volumeMounts:
            - name: mariadb-ps-storage
              mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          name: mariadb
      volumes:
          - name: mariadb-ps-storage
            persistentVolumeClaim:
             claimName: mariadb-pv-claim