apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: guestbook
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: DB_USER
            value: root
          - name: DB_NAME
            value: guestbook  
          - name: DB_HOST
            value: wp-db.wordpress.svc.cluster.local
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name : mariadb-pass
                key: password
        ports:
        - containerPort: 80
          name: guestbook
        lifecycle:
          postStart:
            exec:
              command: ["git", "clone", "https://github.com/qhoa/guestbook.git", "."]